pve_host: 192.168.111.100
pve_api_user: root@pam
# The API password is equivalent to the root password we set on the pve host
pve_api_password: '{{ hostvars["pve"]["pve_root_password"] }}'

# Prefix to differentiate between the provided and our generated template images
lxcostemplate_custom_prefix: custom-

lxccreate_args:
  node: pve # Must be the same as the host that the role is executed on
  cores: 2
  cpuunits: 1024
  memory: 1024
  swap: 0
  disk: "10"
  storage: local-lvm
  nameserver: "8.8.8.8,8.8.4.4"
  searchdomain: "localdomain"
  pubkey: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
  unprivileged: yes
  timeout: 120
  netif:
    # Host-only network for controller/PVE/Container communication (ansible-guests)
    net0: 'name=eth0,bridge=vmbr0,ip={{ hostonly_ip }},firewall=0'
    # Regular Virtualbox NAT for internet access (guests-NAT)
    net1: name=eth1,bridge=vmbr1,ip=dhcp,firewall=0

lxccreate_ostemplate_download: yes
lxccreate_bootstrap: yes
