pve_host: 192.168.111.100
pve_api_user: root@pam
# The API password is equivalent to the root password we set on the pve host
pve_api_password: '{{ hostvars["pve"]["pve_root_password"] }}'

# Prefix to differentiate between the provided and our generated template images
lxcostemplate_custom_prefix: custom-

lxccreate_node: pve # Must be the same as the host that the role is executed on
lxccreate_cores: 2
lxccreate_cpus: 1
lxccreate_cpuunits: 1024
lxccreate_memory: 1024
lxccreate_swap: 0
lxccreate_disk: "10"
lxccreate_storage: local-lvm
lxccreate_mounts: {}
lxccreate_onboot: no
lxccreate_ostemplate_download: yes
lxccreate_nameserver: "8.8.8.8,8.8.4.4"
lxccreate_searchdomain: "localdomain"
lxccreate_password: a-secret-password
lxccreate_pubkey: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
lxccreate_unprivileged: yes
lxccreate_timeout: 120
lxccreate_bootstrap: yes
