authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- tests
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
- .yamllint
- .ansible-lint
- .pre-commit-config.yaml
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- requirements.txt
- requirements-molecule.txt
- '**/requirements-molecule.txt'
- '**/requirements.txt'
dependencies:
  ansible.posix: '>=1.0,<2.0'
description: Collection dealing with Proxmox VE and PBS hosts
issues: https://github.com/maxhoesel-ansible/ansible-collection-proxmox/issues
license:
- GPL-3.0-or-later
license_file: ''
name: proxmox
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-proxmox
tags:
- proxmox
- lxc
- kvm
- virtualization
- pbs
version: 5.0.1
