[tool.autopep8]
max_line_length = 100
ignore = [
    "E402" # Imports at top of file
]

# Pylint settings
[tool.pylint.'NESSAGES CONTROL']
disable=[
    "logging-fstring-interpolation", # See https://github.com/PyCQA/pylint/issues/2354
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring", # also triggers on abstract functions
    "consider-using-enumerate", # not for simple loops
    "consider-using-dict-items",
    "no-else-return",
    "invalid-name",
    "too-many-boolean-expressions",
    "too-few-public-methods",
    "I",
    "wrong-import-position",
    "consider-using-f-string"
]
[tool.pylint.'FORMAT']
max-line-length=100
