---
platforms:
  - name: pbs-client-debian-12
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian12-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: pbs-client-debian-11
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true
