---
platforms:
  # Currently broken because of https://bugzilla.proxmox.com/show_bug.cgi?id=4191
  #- name: pbs-client-ubuntu-22
  #  groups:
  #    - ubuntu
  #  image: "docker.io/geerlingguy/docker-ubuntu2204-ansible"
  #  volumes:
  #    - /sys/fs/cgroup:/sys/fs/cgroup:rw
  #  cgroupns_mode: host
  #  privileged: true
  #  override_command: false
  #  pre_build_image: true

  - name: pbs-client-ubuntu-20
    groups:
      - ubuntu
    image: "docker.io/geerlingguy/docker-ubuntu2004-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true

  - name: pbs-client-debian-11
    groups:
      - debian
    image: "docker.io/geerlingguy/docker-debian11-ansible"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
    pre_build_image: true
