galaxy_info:
  author: Arios <ansible@arios.me>
  description: Create and bootstrap an LXC container on a Proxmox node
  company: ""

  license: GPL-3.0-or-later

  min_ansible_version: 2.9

  platforms:
  - name: Debian
    versions:
    - all

  galaxy_tags:
  - proxmox
  - lxc
  - container
  - bootstrap

dependencies: []
