- name: update initramfs
  command: update-initramfs -u -k all

# These wrapper handlers are needed to ensure that we only reboot when allowed, and only reboot once
- name: reboot host to enable pcie passthrough
  ansible.builtin.debug:
    msg: "Rebooting host to enable pice passthrough"
  changed_when: true
  notify: _reboot host
  when: pve_pcie_reboot_for_kernel

- name: reboot host to update microcode
  ansible.builtin.debug:
    msg: "Rebooting host to update microcode"
  changed_when: true
  notify: _reboot host
  when: pve_reboot_for_ucode

- name: _reboot host
  ansible.builtin.reboot:
    reboot_timeout: 900

- name: restart cpu-governor service
  ansible.builtin.systemd:
    name: cpu-governor.service
    state: restarted
