- ansible.builtin.include_tasks: check.yml # noqa unnamed-task
- block:
  - ansible.builtin.include_tasks: install.yml # noqa unnamed-task
  - ansible.builtin.include_tasks: configure.yml # noqa unnamed-task
  when: pbs_client_configure_backup
  become: yes
