lxccreate_hostname: '{{ lxcostemplate_custom_prefix }}centos-8'
lxccreate_ostemplate: 'local:vztmpl/{{ lxcostemplate_custom_prefix }}centos-8-default_20191016_amd64.tar.gz'
hostonly_ip: 192.168.111.221/24
