---
- name: Generate module argument dict [1/2]
  set_fact:
    lxccreate_special_args:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      hostname: "{{ lxccreate_hostname }}"
      ostemplate: "{{ lxccreate_ostemplate }}"
      timeout: "{{ lxccreate_timeout }}"
- name: Generate module argument dict [2/2]
  set_fact:
    lxccreate_module_args: "{{ lxccreate_args | combine(lxccreate_special_args) }}"

- name: Download OS Template
  ansible.builtin.include_tasks: ostemplate.yml
  args:
    apply:
      delegate_to: "{{ pve_host }}"

- name: Provision container
  ansible.builtin.include_tasks: provision.yml

- name: Boostrap container
  ansible.builtin.include_tasks: bootstrap.yml
  when: lxccreate_bootstrap and pve_lxccreate_task.changed
  args:
    apply:
      delegate_to: "{{ pve_host }}"
