---
- name: Show deprecation warning
  fail:
    msg: >
      [DEPRECATION WARNING] This role is not actively maintained anymore and will be removed in release 4.0 of this collection.
      It is recommended that you switch your existing playbooks to proxmox modules, or pin your collection dependency at <4.0.
  ignore_errors: true

- name: Generate module argument dict [1/2]
  set_fact:
    lxccreate_special_args:
      api_host: "{{ pve_api_host }}"
      api_user: "{{ pve_api_user }}"
      api_password: "{{ pve_api_password }}"
      hostname: "{{ lxccreate_hostname }}"
      ostemplate: "{{ lxccreate_ostemplate }}"
      timeout: "{{ lxccreate_timeout }}"
- name: Generate module argument dict [2/2]
  set_fact:
    lxccreate_module_args: "{{ lxccreate_args | combine(lxccreate_special_args) }}"

- include: ostemplate.yml
  delegate_to: "{{ pve_host }}"
- include: provision.yml
- include: bootstrap.yml
  delegate_to: "{{ pve_host }}"
  when: lxccreate_bootstrap and pve_lxccreate_task.changed
