- name: Container is present
  proxmox: '{{ lxccreate_module_args }}'
  delegate_to: localhost
  register: pve_lxccreate_task
- name: Wait for PVE API sync
  pause:
    seconds: 10
- name: Container is started
  proxmox:
    api_host: '{{ pve_api_host }}'
    api_user: '{{ pve_api_user }}'
    api_password: '{{ pve_api_password }}'
    hostname: '{{ lxccreate_hostname }}'
    state: started
  delegate_to: localhost
