---
- hosts: localhost
  gather_facts: no
  vars:
    pve_box_name: pve-current
    tmp_dir: ~/.cache/vagrant_pve_build
  pre_tasks:
  - name: Check for existing pve box
    shell: 'vagrant box list --machine-readable | cut -d"," -f 4 | grep {{ pve_box_name }}'
    ignore_errors: yes
    changed_when: no
    register: vagrant_boxes
  - name: Box already exists - skip install
    meta: end_play
    when: pve_box_name in vagrant_boxes.stdout
  tasks:
  - name: Working directory is present
    file:
      path: '{{ tmp_dir }}'
      state: directory
      mode: 0750
  - name: Source repository is cloned
    git:
      repo: https://github.com/rgl/proxmox-ve.git
      depth: 1
      version: master
      dest: '{{ tmp_dir }}/proxmox-ve'
  - name: Patch disk size to accomodate guests
    lineinfile:
      path: '{{ tmp_dir }}/proxmox-ve/proxmox-ve.json'
      regexp: '"disk_size": "15375",'
      line: '"disk_size": "51200",'
  - name: Create PVE image
    command: make build-virtualbox
    args:
      chdir: '{{ tmp_dir }}/proxmox-ve'
    when: not pve_box_name in vagrant_boxes.stdout # make ansible-lint happy
  - name: Add PVE image as box
    command: 'vagrant box add -f proxmox-ve-amd64-virtualbox.box --name {{ pve_box_name }}'
    args:
      chdir: '{{ tmp_dir }}/proxmox-ve'
    when: not pve_box_name in vagrant_boxes.stdout # make ansible-lint happy
  - name: Remove working directory
    file:
      path: '{{ tmp_dir }}'
      state: absent
