---
dependency:
  name: shell
  command: ansible-playbook molecule/lxc/dependency.yml

lint: |
  set -e
  ansible-lint roles/lxc_* molecule/**/*.yml
  yamllint .

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: pve
    box: pve-current
    memory: 4096
    cpus: 4
    interfaces:
    # NET2 - Host-only net for ansible access
    - network_name: private_network
      type: static
      ip: "192.168.111.100/24"
    provider_raw_config_args:
    # Hardware-assisted nested virtualization for KVM guests
    - "customize ['modifyvm', :id, '--nested-hw-virt', 'on']"
    # Promiscious mode on NET2 to allow nested guests network access
    - "customize ['modifyvm', :id, '--nicpromisc2', 'allow-all']"
    # NET3 - internet access for guests
    - "customize ['modifyvm', :id, '--nic3', 'nat']"
    groups:
    - pve_nodes

provisioner:
  name: ansible
  config_options:
    defaults:
      host_key_checking: no
  inventory:
    links:
      hosts: inventory/hosts.yml
      group_vars: inventory/group_vars
      host_vars: inventory/host_vars

verifier:
  name: ansible
