---
- name: Verify lxc_containers
  hosts: containers
  remote_user: root
  gather_facts: no
  tasks:
  - name: Verify connection and Ansible execution on bootstrapped containers
    setup:

- name: Create containers from generated ostemplates
  hosts: custom_containers
  gather_facts: no
  roles:
  - name: ../../roles/lxc_container
    lxccreate_bootstrap: no
    lxccreate_ostemplate_download: no

- name: Verify new containers
  hosts: custom_containers
  remote_user: root
  gather_facts: no
  tasks:
  - name: Wait for containers to start
    wait_for_connection:
  - name: Verify connection and Ansible execution on containers from ostemplate
    setup:
