---
# This role needs API and SSH access to a PVE node with become privileges
# in order to create a container. Please set pve_host to the corresponding
# inventory hostname
pve_host: pve.example.com
pve_api_host: '{{ pve_host }}'
pve_api_user: root@pam
pve_api_password: mypassword

# The parameters of the container. See
# https://docs.ansible.com/ansible/latest/modules/proxmox_module.html
# for details about each parameter
# The PVE node to create the container on
lxccreate_node: pve # Must be the same as the host that the role is executed on
lxccreate_hostname: my-container
lxccreate_cores: 1
lxccreate_cpus: 1
lxccreate_cpuunits: 1024
lxccreate_memory: 1024
lxccreate_swap: 0
lxccreate_disk: "10"
lxccreate_storage: local-lvm
lxccreate_mounts: {}
lxccreate_onboot: no
# Use this ostemplate (base image) to create the container
lxccreate_ostemplate: local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz
# Automatically download the specified base template from the PVE repository if the image is not present
lxccreate_ostemplate_download: yes
# Dict of network interfaces. See the PVE API for all valid parameters
# https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/lxc
lxccreate_netif:
  net0: name=eth0,bridge=vmbr0,ip=192.168.1.10/24,gw=192.168.1.1,firewall=0
lxccreate_nameserver: "8.8.8.8,8.8.4.4"
lxccreate_searchdomain: "localdomain"
lxccreate_password: a-secret-password
lxccreate_pubkey: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
lxccreate_unprivileged: yes

# Increase this value if you are experiencing timeout errors during PVE API tasks
lxccreate_timeout: 120

# Set this to no if you want to skip bootstrapping the container
# (ssh server, python)
lxccreate_bootstrap: yes
